In [1]:
import sklearn
print(sklearn.__version__)

0.20.1


In [2]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [3]:
import pandas as pd

# 학습은 .fit(), 예측은 .predict()

In [4]:
#붓꽃 데이터셋 로딩
iris=load_iris()

In [5]:
#iris_data: 데이터셋에서 피처만으로 된 데이터(numpy형태)
iris_data=iris.data

#iris_target
 ##앞으로 나올 target=label 같은 의미!!
iris_target=iris.target
print('iris target: ', iris_target)
print('iris target name: ', iris.target_names)

iris target:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target name:  ['setosa' 'versicolor' 'virginica']


In [6]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [7]:
#붓꽃 데이터셋 df 변환(iris_data)
df=pd.DataFrame(data=iris_data, columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [8]:
#붓꽃 데이터셋 df변환2(iris_target)
df['label']=pd.DataFrame(data=iris_target)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

In [9]:
#트레이닝/테스트 데이터 분리
##random_state는 seed의 개념(지정 안하면 할때마다 무작위로 데이터셋 분리)
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_target, test_size=0.2, random_state=11)

In [10]:
#decision tree 객체 생성
dt_clf= DecisionTreeClassifier(random_state=11)

#학습 수행
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=11,
            splitter='best')

In [11]:
#학습 끝! 이제 예측.(반드시 학습에 쓴 게 아닌 다른 데이터 이용해야 함-test 데이터셋으로)
pred = dt_clf.predict(X_test)

In [12]:
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [13]:
#모델 성능 평가: 정확도 측정(예측값이 실제 레이블 값과 얼마나 정확하게 맞는가? 'pred'와 'y_test'비교하면 되겠지?)
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.9333


-

In [15]:
#붓꽃 데이터 세트 뜯어보기

from sklearn.datasets import load_iris
iris_data=load_iris()
print(type(iris_data))

<class 'sklearn.utils.Bunch'>


In [16]:
iris_data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [18]:
print('\n feature_names의 type: ', type(iris_data.feature_names))
print('\n feature_names의 shape: ', len(iris_data.feature_names))
print(iris_data.feature_names)


 feature_names의 type:  <class 'list'>

 feature_names의 shape:  4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [19]:
print('\n target_names의 type: ', type(iris_data.target_names))
print('\n target_names의 shape: ', len(iris_data.target_names))
print(iris_data.target_names)


 target_names의 type:  <class 'numpy.ndarray'>

 target_names의 shape:  3
['setosa' 'versicolor' 'virginica']


In [21]:
print('\n data의 type: ', type(iris_data.data))
print('\n data의 shape: ', iris_data.data.shape) #(150,4)의 2차원 데이터
print(iris_data['data'])


 data의 type:  <class 'numpy.ndarray'>

 data의 shape:  (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5. 

In [22]:
print('\n target의 type: ', type(iris_data.target))
print('\n target의 shape: ', iris_data.target.shape) #(150,)의 1차원 데이터
print(iris_data.target)


 target의 type:  <class 'numpy.ndarray'>

 target의 shape:  (150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


# model seleciton 모듈

- train_test_split()
- 교차 검증 분할 및 평가
- Estimator의 하이퍼 파라미터를 튜닝하기 위한 다양한 함수&클래스 제공

In [3]:
#트레이닝/테스트 데이터 분리 : train_test_split()
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [4]:
#데이터셋 로드
iris=load_iris()
dt_clf=DecisionTreeClassifier()

#train/test로 나누지 않고 train dataset으로 학습+예측 다 했을 경우.
train_data=iris.data
train_label=iris.target

#학습
dt_clf.fit(train_data,train_label)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [5]:
#예측
pred = dt_clf.predict(train_data)
print('예측 정확도: ', accuracy_score(train_label, pred)) #그래서 정확도가 100%.... 잘못 나온 거겠죠?

예측 정확도:  1.0


** 위의 경우는 틀렸습니다! train/test 로 데이터셋을 나눠줘야죠!
그리고 학습은 trainset으로, 예측은 testset으로!

In [4]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [5]:
dt_clf=DecisionTreeClassifier()
iris_data=load_iris()

#데이터셋 분리
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.3, random_state=121)

In [8]:
#학습
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [10]:
#예측
pred=dt_clf.predict(X_test)
print('예측 정확도: ', accuracy_score(y_test, pred))

예측 정확도:  0.9555555555555556


# 교차 검증(cross validation)

- 데이터를 training/ test 분할 후
- training 데이터를 다시 분할하여 학습 데이터와 검증 세이터세트로 나눔.(여기서 학습+평가 수행)
- 이 과정을 거치면, 하이퍼 파라미터 튜닝 등의 모델 최적화를 더욱 손쉽게 할 수 있음.

※ k-fold

In [1]:
#k-fold 교차 검증
#k=5
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

In [6]:
iris=load_iris()
features=iris.data
label=iris.target
dt_clf=DecisionTreeClassifier(random_state=156)

In [16]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [7]:
kfold=KFold(n_splits=5)
cv_accuracy=[] #나중에 5번 계속 반복하면서 정확도를 append할 것임.
print('붓꽃 데이터 세트 크기: ', features.shape[0])

붓꽃 데이터 세트 크기:  150


In [8]:
features.shape

(150, 4)

In [9]:
kfold #전체 데이터셋이 150개인데, 5개로 분할했으므로 30개씩 나뉘게 됨. 여기서 학습용은 120개 + 검증용은 30개

KFold(n_splits=5, random_state=None, shuffle=False)

In [10]:
features

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [21]:
kfold.split(features)

<generator object _BaseKFold.split at 0x000001F757628138>

In [22]:
n_iter=0

#KFold 객체의 split()을 호출하면 폴드별 학습용, 검증용 데이터의 row index를 array로 반환.

#kfold.split 만큼 하는것이므로, 이거 총 5번 반복하게 됨.
for train_index, test_index in kfold.split(features):
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    
    dt_clf.fit(X_train, y_train) #학습
    pred = dt_clf.predict(X_test) #예측
    n_iter +=1
    
    #반복 시마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n#{0} 교차 검증 정확도 :{1}, 학습용데이터 크기: {2}, 검증용데이터 크기: {3}'.format(n_iter, accuracy, train_size, test_size))
    print('#{0} 테스트 세트 인덱스:{1}'.format(n_iter, train_index))
    print("#{0} 검증 세트 인덱스:{1}".format(n_iter, test_index))
    cv_accuracy.append(accuracy)


#1 교차 검증 정확도 :1.0, 학습용데이터 크기: 120, 검증용데이터 크기: 30
#1 테스트 세트 인덱스:[ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47
  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
#1 검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도 :0.9667, 학습용데이터 크기: 120, 검증용데이터 크기: 30
#2 테스트 세트 인덱스:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97

In [19]:
cv_accuracy

[1.0, 0.9667, 0.8667, 0.9333, 0.7333]

In [20]:
#개별 iter 별 정확도를 합하여, 평균 정확도는?
print('## 평균 검증 정확도: ', np.mean(cv_accuracy))

## 평균 검증 정확도:  0.9


※ Stratified k-fold

In [23]:
#불균형한 분포도를 가진 레이블 데이터 집합을 위한 k-fold.
#즉, 특정 레이블 값이 특이하게 많거나 or 매우 적어서 값의 분포가 한쪽으로 치우친 데이터. ex)대출 사기

import pandas as pd

iris=load_iris()
iris_df=pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()

2    50
1    50
0    50
Name: label, dtype: int64

In [24]:
#k=3 인 k-fold
kfold=KFold(n_splits=3)

In [31]:
n_iter=0
for train_index, test_index in kfold.split(iris_df): #k가 3개
    n_iter +=1
    label_train=iris_df['label'].iloc[train_index]
    label_test=iris_df['label'].iloc[test_index]
    print("#교차 검증: {0}".format(n_iter))
    print("학습 label 데이터 분포:\n", label_train.value_counts())
    print("검증 label 데이터 분포:\n", label_test.value_counts())
    
#결과값을 보면, trainingset과 testset의 레이블이 완전히 다른 레이블임.

#교차 검증: 1
학습 label 데이터 분포:
 2    50
1    50
Name: label, dtype: int64
검증 label 데이터 분포:
 0    50
Name: label, dtype: int64
#교차 검증: 2
학습 label 데이터 분포:
 2    50
0    50
Name: label, dtype: int64
검증 label 데이터 분포:
 1    50
Name: label, dtype: int64
#교차 검증: 3
학습 label 데이터 분포:
 1    50
0    50
Name: label, dtype: int64
검증 label 데이터 분포:
 2    50
Name: label, dtype: int64


In [28]:
#그래서 이 경우에 accuracy는....
n_iter=0
for train_index, test_index in kfold.split(features):
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    
    dt_clf.fit(X_train, y_train) #학습
    pred = dt_clf.predict(X_test) #예측
    n_iter +=1
    
    #반복 시마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n#{0} 교차 검증 정확도 :{1}, 학습용데이터 크기: {2}, 검증용데이터 크기: {3}'.format(n_iter, accuracy, train_size, test_size)) #아예 정확도가 0
    print("#{0} 검증 세트 인덱스:{1}".format(n_iter, test_index))
    cv_accuracy.append(accuracy)


#1 교차 검증 정확도 :0.0, 학습용데이터 크기: 100, 검증용데이터 크기: 50
#1 검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]

#2 교차 검증 정확도 :0.0, 학습용데이터 크기: 100, 검증용데이터 크기: 50
#2 검증 세트 인덱스:[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]

#3 교차 검증 정확도 :0.0, 학습용데이터 크기: 100, 검증용데이터 크기: 50
#3 검증 세트 인덱스:[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]


In [29]:
np.mean(cv_accuracy)

0.5625

- 그러니까 이런 경우엔, kfold 말고 stratifiedkfold를 써줍시다! (아님 k의 값을 늘려도 되구!)

In [36]:
from sklearn.model_selection import StratifiedKFold

skf=StratifiedKFold(n_splits=3)
n_iter=0

In [37]:
for train_index, test_index in skf.split(iris_df, iris_df['label']):
    n_iter +=1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print("\n#교차 검증: {0}".format(n_iter))
    print("학습 label 데이터 분포:\n", label_train.value_counts())
    print("검증 label 데이터 분포:\n", label_test.value_counts())


#교차 검증: 1
학습 label 데이터 분포:
 2    33
1    33
0    33
Name: label, dtype: int64
검증 label 데이터 분포:
 2    17
1    17
0    17
Name: label, dtype: int64

#교차 검증: 2
학습 label 데이터 분포:
 2    33
1    33
0    33
Name: label, dtype: int64
검증 label 데이터 분포:
 2    17
1    17
0    17
Name: label, dtype: int64

#교차 검증: 3
학습 label 데이터 분포:
 2    34
1    34
0    34
Name: label, dtype: int64
검증 label 데이터 분포:
 2    16
1    16
0    16
Name: label, dtype: int64


In [39]:
#직접 Stratifiedkfold를 이용한 교차 검증 수행해 봅시다!
dt_clf= DecisionTreeClassifier(random_state=156)
skfold=StratifiedKFold(n_splits=3)
n_iter=0
cv_accuracy=[]

#StratifiedKFold의 split() 호출 시 반드시 레이블 데이터셋도 추가 입력 필요
for train_index, test_index in skfold.split(features, label):
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    
    dt_clf.fit(X_train, y_train) #학습
    pred = dt_clf.predict(X_test) #예측
    n_iter +=1
    
    #반복 시마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n#{0} 교차 검증 정확도 :{1}, 학습용데이터 크기: {2}, 검증용데이터 크기: {3}'.format(n_iter, accuracy, train_size, test_size))
    print("#{0} 검증 세트 인덱스:{1}".format(n_iter, test_index))
    cv_accuracy.append(accuracy)


#1 교차 검증 정확도 :0.9804, 학습용데이터 크기: 99, 검증용데이터 크기: 51
#1 검증 세트 인덱스:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116]

#2 교차 검증 정확도 :0.9216, 학습용데이터 크기: 99, 검증용데이터 크기: 51
#2 검증 세트 인덱스:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133]

#3 교차 검증 정확도 :0.9792, 학습용데이터 크기: 102, 검증용데이터 크기: 48
#3 검증 세트 인덱스:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]


In [40]:
#교차검증별 정확도 및 평균 정확도
print('#교차검증별 정확도: ', np.round(cv_accuracy, 4))
print("##평균 검증 정확도: ", np.mean(cv_accuracy))

#교차검증별 정확도:  [0.9804 0.9216 0.9792]
##평균 검증 정확도:  0.9604


## 앞의 이 모든 교차 검증을 한번에 해주는 게 있다?! : cross_val_score()

- cross_val_score의 분할은 StratifiedKFold를 따름.

In [43]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

In [45]:
iris_data=load_iris()
dt_clf=DecisionTreeClassifier(random_state=156)

data=iris_data.data
label=iris_data.target

In [46]:
#이렇게 쓰는 것! cross_val_score(estimator, X, y, scoring='accuracy', cv=k개수.)
cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)

array([0.98039216, 0.92156863, 0.97916667])

In [49]:
print("교차 검증별 정확도:", np.round(cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3), 4))
print("평균 검증 정확도:", np.round(np.mean(cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)),4))

교차 검증별 정확도: [0.9804 0.9216 0.9792]
평균 검증 정확도: 0.9604


## 교차 검증과 최적 하이퍼 파라미터 튜닝을 한번에! : GridSearchCV 

- 하이퍼 파라미터: 머신러닝 알고리즘을 구성하는 주요 구성 요소, 이 값을 조정해 알고리즘의 예측 성능 개선 가능.
- gridseachCV 방법은  여러 하이퍼 파라미터를 순차적으로 변경하면서 최적의 파라미터를 도출한다.

In [13]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score

In [3]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [4]:
iris_data=load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=121)
dtree=DecisionTreeClassifier()

#파라미터를 딕셔너리 형태로 설정
param={'max_depth':[1,2,3], 'min_samples_split':[2,3]} #3x2 라서 파라미터 조합은 6임. #cv는 3이므로, 3x6=총 18번 수행하게 됨.

In [5]:
import pandas as pd

#param_grid의 하이퍼 파라미터를 3개의 train, testset fold로 나눠 테스트 수행 설정.
##refit=True가 디폴트. Ture면 가장 좋은 파라미터 설정으로 재학습시킴

grid_dtree = GridSearchCV(dtree, param_grid=param, cv=3, refit=True)

#붓꽃 학습 데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습/평가
grid_dtree.fit(X_train, y_train)

#GridSearchCV 결과를 추출해 dataframe 변환
score_df=pd.DataFrame(grid_dtree.cv_results_)
score_df

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split2_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\util

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.001330      0.001881         0.000998        0.000003   
1       0.000000      0.000000         0.000665        0.000470   
2       0.000332      0.000470         0.000332        0.000470   
3       0.000665      0.000470         0.000000        0.000000   
4       0.000333      0.000471         0.000332        0.000469   
5       0.000664      0.000470         0.000332        0.000470   

  param_max_depth param_min_samples_split  \
0               1                       2   
1               1                       3   
2               2                       2   
3               2                       3   
4               3                       2   
5               3                       3   

                                     params  split0_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}              0.700   
1  {'max_depth': 1, 'min_samples_split': 3}              0.700   
2  {'max_depth': 2, 'min_samples_split': 2}              0.925   
3  {'max_depth': 2, 'min_samples_split': 3}              0.925   
4  {'max_depth': 3, 'min_samples_split': 2}              0.975   
5  {'max_depth': 3, 'min_samples_split': 3}              0.975   

   split1_test_score  split2_test_score  mean_test_score  std_test_score  \
0                0.7               0.70         0.700000        0.000000   
1                0.7               0.70         0.700000        0.000000   
2                1.0               0.95         0.958333        0.031180   
3                1.0               0.95         0.958333        0.031180   
4                1.0               0.95         0.975000        0.020412   
5                1.0               0.95         0.975000        0.020412   

   rank_test_score  split0_train_score  split1_train_score  \
0                5              0.7000              0.7000   
1                5              0.7000              0.7000   
2                3              0.9750              0.9375   
3                3              0.9750              0.9375   
4                1              0.9875              0.9625   
5                1              0.9875              0.9625   

   split2_train_score  mean_train_score  std_train_score  
0              0.7000          0.700000     1.110223e-16  
1              0.7000          0.700000     1.110223e-16  
2              0.9625          0.958333     1.559024e-02  
3              0.9625          0.958333     1.559024e-02  
4              0.9875          0.979167     1.178511e-02  
5              0.9875          0.979167     1.178511e-02

In [6]:
score_df[['params','mean_test_score','rank_test_score','split0_test_score','split1_test_score','split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [8]:
#최고 성능의 최적의 파라미터(params)는?
grid_dtree.best_params_

{'max_depth': 3, 'min_samples_split': 2}

In [9]:
#최적의 파라미터의 스코어 값은?
grid_dtree.best_score_

0.975

In [14]:
#gridsearchCV의 refit으로 이미 학습된 estimator 반환
estimator=grid_dtree.best_estimator_

#그리고 위의 best_estimator_는 이미 최적 학습이 되었으므로 별도의 학습이 필요 없음.
pred= estimator.predict(X_test)
print("테스트 데이터셋 정확도: {0:.4f}".format(accuracy_score(y_test,pred)))

테스트 데이터셋 정확도: 0.9667
